// Label delivery: download label, then fan out to Brevo / Gmail / local print.
const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');
const { sendMail } = require('./smtp');

const LABELS = path.join(__dirname, '..', 'labels');

async function downloadLabel(url, orderId) {
  if (!url) throw new Error('No label url to download');
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Label download failed: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const ext = url.toLowerCase().includes('.pdf') ? 'pdf'
    : url.toLowerCase().includes('.zpl') ? 'zpl' : 'png';
  const file = path.join(LABELS, `label_${orderId}.${ext}`);
  fs.writeFileSync(file, buf);
  return { file, buf, ext };
}

function contentType(ext) {
  return ext === 'pdf' ? 'application/pdf' : ext === 'zpl' ? 'text/plain' : 'image/png';
}

async function sendBrevo(cfg, { to, subject, text, filename, content, ext }) {
  const res = await fetch('https://api.brevo.com/v3/smtp/email', {
    method: 'POST',
    headers: { 'api-key': cfg.apiKey, 'Content-Type': 'application/json', 'Accept': 'application/json' },
    body: JSON.stringify({
      sender: { email: cfg.from, name: cfg.fromName || 'Shipping' },
      to: [{ email: to }],
      subject,
      textContent: text,
      attachment: [{ name: filename, content: content.toString('base64') }],
    }),
  });
  if (!res.ok) throw new Error(`Brevo send failed: HTTP ${res.status} ${await res.text()}`);
  return true;
}

function printLabel(printCfg, file) {
  return new Promise((resolve, reject) => {
    const args = [];
    if (printCfg.printer) args.push('-d', printCfg.printer);
    if (printCfg.media) args.push('-o', `media=${printCfg.media}`);
    args.push('-o', 'fit-to-page', file);
    execFile('lp', args, (err, stdout, stderr) => {
      if (err) return reject(new Error(`lp failed: ${stderr || err.message}`));
      resolve(stdout.trim());
    });
  });
}

// Fan out. Returns an array of {channel, ok, detail}.
async function deliver(order, label, settings) {
  const d = settings.delivery || {};
  const results = [];
  const subject = `Dalmend label - Order #${order.number} (${order.shipping.name})`;
  const text = [
    `Shipping label for order #${order.number}`,
    `Recipient: ${order.shipping.name}, ${order.shipping.city} ${order.shipping.province_code}`,
    `Package: ${order.pkg ? order.pkg.boxName : ''} ${order.pkg ? order.pkg.weight + 'g' : ''}`,
    order.tracking ? `Tracking: ${order.tracking}` : '',
    order.cost ? `Postage: ${order.cost}` : '',
    '',
    'Generated by Nexus ChitChats Auto.',
  ].filter(Boolean).join('\n');

  const filename = `label_${order.number}.${label.ext}`;
  const ct = contentType(label.ext);

  if (d.brevo && d.brevo.enabled && d.brevo.apiKey) {
    try {
      await sendBrevo(d.brevo, { to: d.brevo.to, subject, text, filename, content: label.buf, ext: label.ext });
      results.push({ channel: 'brevo', ok: true, detail: `sent to ${d.brevo.to}` });
    } catch (e) { results.push({ channel: 'brevo', ok: false, detail: e.message }); }
  }

  if (d.gmail && d.gmail.enabled && d.gmail.user && d.gmail.appPassword) {
    try {
      await sendMail({
        host: 'smtp.gmail.com', port: 465,
        user: d.gmail.user, pass: d.gmail.appPassword,
        from: d.gmail.user, fromName: 'Dalmend Shipping',
        to: d.gmail.to || d.gmail.user,
        subject, text,
        attachment: { filename, content: label.buf, contentType: ct },
      });
      results.push({ channel: 'gmail', ok: true, detail: `sent to ${d.gmail.to || d.gmail.user}` });
    } catch (e) { results.push({ channel: 'gmail', ok: false, detail: e.message }); }
  }

  if (d.print && d.print.enabled) {
    try {
      const out = await printLabel(d.print, label.file);
      results.push({ channel: 'print', ok: true, detail: out || 'queued' });
    } catch (e) { results.push({ channel: 'print', ok: false, detail: e.message }); }
  }

  // dashboard is always available (label stored on disk)
  results.push({ channel: 'dashboard', ok: true, detail: path.basename(label.file) });
  return results;
}

module.exports = { downloadLabel, deliver, LABELS };
